pipeline {
    agent any
    parameters {
        choice(name: 'NUMBER',
            choices: [10,20,30,40,50,60,70,80,90],
            description: 'Select the value for F(n) for the Fibonnai sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    triggers {
        cron '@midnight'
    }
    stages {
        stage('Make executable') {
            steps {
                echo  "BUILD_DISPLAY_NAME         =  ${BUILD_DISPLAY_NAME}"
                echo  "BUILD_ID                   =  ${BUILD_ID}"
                echo  "BUILD_NUMBER               =  ${BUILD_NUMBER}"
                echo  "BUILD_TAG                  =  ${BUILD_TAG}"
                echo  "BUILD_URL                  =  ${BUILD_URL}"
                echo  "CI                         =  ${CI}"
                echo  "EXECUTOR_NUMBER            =  ${EXECUTOR_NUMBER}"
                echo  "JENKINS_HOME               =  ${JENKINS_HOME}"
                echo  "JENKINS_URL                =  ${JENKINS_URL}"
                echo  "JOB_BASE_NAME              =  ${JOB_BASE_NAME}"
                echo  "JOB_DISPLAY_URL            =  ${JOB_DISPLAY_URL}"
                echo  "JOB_NAME                   =  ${JOB_NAME}"
                echo  "JOB_URL                    =  ${JOB_URL}"
                echo  "NODE_LABELS                =  ${NODE_LABELS}"
                echo  "NODE_NAME                  =  ${NODE_NAME}"
                echo  "RUN_ARTIFACTS_DISPLAY_URL  =  ${RUN_ARTIFACTS_DISPLAY_URL}"
                echo  "RUN_CHANGES_DISPLAY_URL    =  ${RUN_CHANGES_DISPLAY_URL}"
                echo  "RUN_DISPLAY_URL            =  ${RUN_DISPLAY_URL}"
                echo  "RUN_TESTS_DISPLAY_URL      =  ${RUN_TESTS_DISPLAY_URL}"
                echo  "WORKSPACE                  =  ${WORKSPACE}"
                echo  "WORKSPACE_TMP              =  ${WORKSPACE_TMP}"
                sh('chmod +x ./scripts/fibonacci.sh')
            }
        }
        stage('Relative path') {
            steps {
                sh("./scripts/fibonacci.sh ${env.NUMBER}")
            }
        }
        stage('Full path') {
            steps {
                sh("${env.WORKSPACE}/scripts/fibonacci.sh ${env.NUMBER}")
            }
        }
        stage('Change directory') {
            steps {
                dir("${env.WORKSPACE}/scripts"){
                    sh("./fibonacci.sh ${env.NUMBER}")
                }
            }
        }
    }
}
